Algoritmo "declaracaoDeVariaveis"


Var
// declarando as variaveis
   a : inteiro
   b : real
   c : caracter
   d : logico


Inicio
//inserindo valores das variaveis
     a <- 32
     b <- 2.34567
     c <- "Bom dia!"
     d <- VERDADEIRO
//solicitando ao sistema para ESCREVER oque foi inserido nas variaveis
     escreval(a)
     escreval(b)
     escreval(c)
     escreval(d)



Fimalgoritmo
